"""Fix missing constraint

Revision ID: 548ea7921e6b
Revises: 92a7b9f03f89
Create Date: 2025-03-24 20:00:10.894124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '548ea7921e6b'
down_revision: Union[str, None] = '92a7b9f03f89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_ident',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('user_first_name', sa.String(), nullable=False),
    sa.Column('user_last_name', sa.String(), nullable=False),
    sa.Column('user_state', sa.String(), nullable=True),
    sa.Column('user_image', sa.String(), nullable=True),
    sa.Column('user_auth_password', sa.String(), nullable=True),
    sa.Column('user_auth_google', sa.String(), nullable=True),
    sa.Column('user_auth_expiration', sa.DateTime(), nullable=True),
    sa.Column('user_auth_cookie', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    schema='sensitive'
    )
    op.create_table('user_legislator',
    sa.Column('user_legislator_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('bioguide_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['bioguide_id'], ['legislator.bioguide_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['sensitive.user_ident.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_legislator_id'),
    schema='sensitive'
    )
    op.create_index(op.f('ix_sensitive_user_legislator_bioguide_id'), 'user_legislator', ['bioguide_id'], unique=False, schema='sensitive')
    op.create_index(op.f('ix_sensitive_user_legislator_user_id'), 'user_legislator', ['user_id'], unique=False, schema='sensitive')
    op.create_table('user_usc_content_folder',
    sa.Column('user_usc_content_folder_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['sensitive.user_ident.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_usc_content_folder_id'),
    schema='sensitive'
    )
    op.create_index(op.f('ix_sensitive_user_usc_content_folder_user_id'), 'user_usc_content_folder', ['user_id'], unique=False, schema='sensitive')
    op.create_table('legislation_action',
    sa.Column('legislation_action_id', sa.Integer(), nullable=False),
    sa.Column('legislation_id', sa.Integer(), nullable=True),
    sa.Column('action_date', sa.Date(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('action_type', sa.String(), nullable=True),
    sa.Column('action_code', sa.String(), nullable=True),
    sa.Column('source_code', sa.String(), nullable=True),
    sa.Column('source_name', sa.String(), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['legislation_id'], ['legislation.legislation_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('legislation_action_id')
    )
    op.create_index(op.f('ix_legislation_action_legislation_id'), 'legislation_action', ['legislation_id'], unique=False)
    op.create_table('legislation_vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('chamber', sa.Enum('House', 'Senate', name='legislationchamber'), nullable=True),
    sa.Column('congress_id', sa.Integer(), nullable=True),
    sa.Column('legislation_id', sa.Integer(), nullable=True),
    sa.Column('question', sa.String(), nullable=True),
    sa.Column('independent', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('republican', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('democrat', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('total', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['congress_id'], ['congress.congress_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['legislation_id'], ['legislation.legislation_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legislation_vote_congress_id'), 'legislation_vote', ['congress_id'], unique=False)
    op.create_index(op.f('ix_legislation_vote_id'), 'legislation_vote', ['id'], unique=False)
    op.create_index(op.f('ix_legislation_vote_legislation_id'), 'legislation_vote', ['legislation_id'], unique=False)
    op.create_index(op.f('ix_legislation_vote_number'), 'legislation_vote', ['number'], unique=False)
    op.create_index(op.f('ix_legislation_vote_question'), 'legislation_vote', ['question'], unique=False)
    op.create_table('user_legislation',
    sa.Column('user_legislation_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('legislation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['legislation_id'], ['legislation.legislation_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['sensitive.user_ident.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_legislation_id'),
    schema='sensitive'
    )
    op.create_index(op.f('ix_sensitive_user_legislation_legislation_id'), 'user_legislation', ['legislation_id'], unique=False, schema='sensitive')
    op.create_index(op.f('ix_sensitive_user_legislation_user_id'), 'user_legislation', ['user_id'], unique=False, schema='sensitive')
    op.create_table('user_usc_content',
    sa.Column('user_usc_content_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('user_usc_content_folder_id', sa.Integer(), nullable=True),
    sa.Column('usc_ident', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['sensitive.user_ident.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_usc_content_folder_id'], ['sensitive.user_usc_content_folder.user_usc_content_folder_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_usc_content_id'),
    schema='sensitive'
    )
    op.create_index(op.f('ix_sensitive_user_usc_content_user_id'), 'user_usc_content', ['user_id'], unique=False, schema='sensitive')
    op.create_index(op.f('ix_sensitive_user_usc_content_user_usc_content_folder_id'), 'user_usc_content', ['user_usc_content_folder_id'], unique=False, schema='sensitive')
    op.create_table('legislator_vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('legislation_vote_id', sa.Integer(), nullable=True),
    sa.Column('legislator_bioguide_id', sa.String(), nullable=True),
    sa.Column('vote', sa.Enum('yay', 'nay', 'present', 'abstain', name='legislatorvotetype'), nullable=True),
    sa.ForeignKeyConstraint(['legislation_vote_id'], ['legislation_vote.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['legislator_bioguide_id'], ['legislator.bioguide_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legislator_vote_id'), 'legislator_vote', ['id'], unique=False)
    op.create_index(op.f('ix_legislator_vote_legislation_vote_id'), 'legislator_vote', ['legislation_vote_id'], unique=False)
    op.create_index(op.f('ix_legislator_vote_legislator_bioguide_id'), 'legislator_vote', ['legislator_bioguide_id'], unique=False)
    op.create_table('user_llm_query',
    sa.Column('user_llm_query_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('legislation_version_id', sa.Integer(), nullable=True),
    sa.Column('query', sa.String(), nullable=False),
    sa.Column('response', sa.String(), nullable=False),
    sa.Column('safe', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['legislation_version_id'], ['legislation_version.legislation_version_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['sensitive.user_ident.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_llm_query_id'),
    schema='sensitive'
    )
    op.create_index(op.f('ix_sensitive_user_llm_query_legislation_version_id'), 'user_llm_query', ['legislation_version_id'], unique=False, schema='sensitive')
    op.create_index(op.f('ix_sensitive_user_llm_query_query'), 'user_llm_query', ['query'], unique=False, schema='sensitive')
    op.create_index(op.f('ix_sensitive_user_llm_query_user_id'), 'user_llm_query', ['user_id'], unique=False, schema='sensitive')
    op.create_table('legislation_action_parse',
    sa.Column('legislation_action_parse_id', sa.Integer(), nullable=False),
    sa.Column('legislation_version_id', sa.Integer(), nullable=True),
    sa.Column('legislation_content_id', sa.Integer(), nullable=True),
    sa.Column('actions', billparser.db.models.CastingArray(JSONB(astext_type=Text())), nullable=True),
    sa.Column('citations', billparser.db.models.CastingArray(JSONB(astext_type=Text())), nullable=True),
    sa.ForeignKeyConstraint(['legislation_content_id'], ['legislation_content.legislation_content_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['legislation_version_id'], ['legislation_version.legislation_version_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('legislation_action_parse_id')
    )
    op.create_index(op.f('ix_legislation_action_parse_legislation_content_id'), 'legislation_action_parse', ['legislation_content_id'], unique=False)
    op.create_index(op.f('ix_legislation_action_parse_legislation_version_id'), 'legislation_action_parse', ['legislation_version_id'], unique=False)
    op.create_table('legislation_version_tag',
    sa.Column('legislation_version_tag_id', sa.Integer(), nullable=False),
    sa.Column('legislation_version_id', sa.Integer(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('prompt_batch_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['legislation_version_id'], ['legislation_version.legislation_version_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prompt_batch_id'], ['prompts.prompt_batch.prompt_batch_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('legislation_version_tag_id')
    )
    op.create_index(op.f('ix_legislation_version_tag_legislation_version_id'), 'legislation_version_tag', ['legislation_version_id'], unique=False)
    op.create_index(op.f('ix_legislation_version_tag_prompt_batch_id'), 'legislation_version_tag', ['prompt_batch_id'], unique=False)
    op.create_index(op.f('ix_legislation_version_tag_tags'), 'legislation_version_tag', ['tags'], unique=False)
    op.drop_constraint('unq_bill', 'legislation', type_='unique')
    op.create_unique_constraint('unq_bill', 'legislation', ['chamber', 'number', 'legislation_type', 'congress_id'])
    op.drop_constraint('legislation_committee_association_legislation_id_fkey', 'legislation_committee_association', type_='foreignkey')
    op.drop_constraint('legislation_committee_association_legislation_committee_id_fkey', 'legislation_committee_association', type_='foreignkey')
    op.create_foreign_key(None, 'legislation_committee_association', 'legislation', ['legislation_id'], ['legislation_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'legislation_committee_association', 'legislation_committee', ['legislation_committee_id'], ['legislation_committee_id'], ondelete='CASCADE')
    op.drop_column('legislation_content', 'action_parse')
    op.add_column('legislator', sa.Column('lis_id', sa.String(), nullable=True))
    op.add_column('legislator', sa.Column('job', sa.Enum('Senator', 'Representative', name='legislatorjob'), nullable=True))
    op.add_column('legislator', sa.Column('congress_id', postgresql.ARRAY(sa.Integer()), nullable=True))
    op.add_column('legislator', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('legislator', sa.Column('image_source', sa.String(), nullable=True))
    op.add_column('legislator', sa.Column('profile', sa.String(), nullable=True))
    op.add_column('legislator', sa.Column('twitter', sa.String(), nullable=True))
    op.add_column('legislator', sa.Column('facebook', sa.String(), nullable=True))
    op.add_column('legislator', sa.Column('youtube', sa.String(), nullable=True))
    op.add_column('legislator', sa.Column('instagram', sa.String(), nullable=True))
    op.create_index(op.f('ix_legislator_lis_id'), 'legislator', ['lis_id'], unique=False)
    op.drop_constraint('usc_content_diff_usc_content_id_fkey', 'usc_content_diff', type_='foreignkey')
    op.create_foreign_key(None, 'usc_content_diff', 'usc_content', ['usc_content_id'], ['usc_content_id'], ondelete='CASCADE')
    op.alter_column('appropriation', 'prompt_batch_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='appropriations')
    op.create_index(op.f('ix_appropriations_appropriation_prompt_batch_id'), 'appropriation', ['prompt_batch_id'], unique=False, schema='appropriations')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appropriations_appropriation_prompt_batch_id'), table_name='appropriation', schema='appropriations')
    op.alter_column('appropriation', 'prompt_batch_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='appropriations')
    op.drop_constraint(None, 'usc_content_diff', type_='foreignkey')
    op.create_foreign_key('usc_content_diff_usc_content_id_fkey', 'usc_content_diff', 'usc_content', ['usc_content_id'], ['usc_content_id'])
    op.drop_index(op.f('ix_legislator_lis_id'), table_name='legislator')
    op.drop_column('legislator', 'instagram')
    op.drop_column('legislator', 'youtube')
    op.drop_column('legislator', 'facebook')
    op.drop_column('legislator', 'twitter')
    op.drop_column('legislator', 'profile')
    op.drop_column('legislator', 'image_source')
    op.drop_column('legislator', 'image_url')
    op.drop_column('legislator', 'congress_id')
    op.drop_column('legislator', 'job')
    op.drop_column('legislator', 'lis_id')
    op.add_column('legislation_content', sa.Column('action_parse', postgresql.ARRAY(postgresql.JSONB(astext_type=sa.Text())), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'legislation_committee_association', type_='foreignkey')
    op.drop_constraint(None, 'legislation_committee_association', type_='foreignkey')
    op.create_foreign_key('legislation_committee_association_legislation_committee_id_fkey', 'legislation_committee_association', 'legislation_committee', ['legislation_committee_id'], ['legislation_committee_id'])
    op.create_foreign_key('legislation_committee_association_legislation_id_fkey', 'legislation_committee_association', 'legislation', ['legislation_id'], ['legislation_id'])
    op.drop_constraint('unq_bill', 'legislation', type_='unique')
    op.create_unique_constraint('unq_bill', 'legislation', ['chamber', 'number', 'legislation_type'])
    op.drop_index(op.f('ix_legislation_version_tag_tags'), table_name='legislation_version_tag')
    op.drop_index(op.f('ix_legislation_version_tag_prompt_batch_id'), table_name='legislation_version_tag')
    op.drop_index(op.f('ix_legislation_version_tag_legislation_version_id'), table_name='legislation_version_tag')
    op.drop_table('legislation_version_tag')
    op.drop_index(op.f('ix_legislation_action_parse_legislation_version_id'), table_name='legislation_action_parse')
    op.drop_index(op.f('ix_legislation_action_parse_legislation_content_id'), table_name='legislation_action_parse')
    op.drop_table('legislation_action_parse')
    op.drop_index(op.f('ix_sensitive_user_llm_query_user_id'), table_name='user_llm_query', schema='sensitive')
    op.drop_index(op.f('ix_sensitive_user_llm_query_query'), table_name='user_llm_query', schema='sensitive')
    op.drop_index(op.f('ix_sensitive_user_llm_query_legislation_version_id'), table_name='user_llm_query', schema='sensitive')
    op.drop_table('user_llm_query', schema='sensitive')
    op.drop_index(op.f('ix_legislator_vote_legislator_bioguide_id'), table_name='legislator_vote')
    op.drop_index(op.f('ix_legislator_vote_legislation_vote_id'), table_name='legislator_vote')
    op.drop_index(op.f('ix_legislator_vote_id'), table_name='legislator_vote')
    op.drop_table('legislator_vote')
    op.drop_index(op.f('ix_sensitive_user_usc_content_user_usc_content_folder_id'), table_name='user_usc_content', schema='sensitive')
    op.drop_index(op.f('ix_sensitive_user_usc_content_user_id'), table_name='user_usc_content', schema='sensitive')
    op.drop_table('user_usc_content', schema='sensitive')
    op.drop_index(op.f('ix_sensitive_user_legislation_user_id'), table_name='user_legislation', schema='sensitive')
    op.drop_index(op.f('ix_sensitive_user_legislation_legislation_id'), table_name='user_legislation', schema='sensitive')
    op.drop_table('user_legislation', schema='sensitive')
    op.drop_index(op.f('ix_legislation_vote_question'), table_name='legislation_vote')
    op.drop_index(op.f('ix_legislation_vote_number'), table_name='legislation_vote')
    op.drop_index(op.f('ix_legislation_vote_legislation_id'), table_name='legislation_vote')
    op.drop_index(op.f('ix_legislation_vote_id'), table_name='legislation_vote')
    op.drop_index(op.f('ix_legislation_vote_congress_id'), table_name='legislation_vote')
    op.drop_table('legislation_vote')
    op.drop_index(op.f('ix_legislation_action_legislation_id'), table_name='legislation_action')
    op.drop_table('legislation_action')
    op.drop_index(op.f('ix_sensitive_user_usc_content_folder_user_id'), table_name='user_usc_content_folder', schema='sensitive')
    op.drop_table('user_usc_content_folder', schema='sensitive')
    op.drop_index(op.f('ix_sensitive_user_legislator_user_id'), table_name='user_legislator', schema='sensitive')
    op.drop_index(op.f('ix_sensitive_user_legislator_bioguide_id'), table_name='user_legislator', schema='sensitive')
    op.drop_table('user_legislator', schema='sensitive')
    op.drop_table('user_ident', schema='sensitive')
    # ### end Alembic commands ###
